```{r}
t.consolidated_tasks <- bind_rows(presentation_data$tasks %>% mutate(Type="Task") %>%
                                     select(Type,Project=Project_Name,Item=Task,State,
                                            assignee,due=end,RAG,
                                            t.Project=Project_Name,
                                            t.RAG,t.Item=t.Task,t.assignee,t.State,
                                            t.due=t.end),
                                   presentation_data$actions %>% mutate(Type="Action") %>%
                                     select(Type,Project,Item=action,State,assignee,
                                            due,RAG,t.RAG,t.Item=t.Action,t.assignee,
                                            t.State,t.due),
                                   presentation_data$issues %>% mutate(Type="Issue") %>%
                                     select(Type,Project,Item=Title,State,assignee=Assignee,
                                            due,RAG,t.RAG,t.Item=t.Title,
                                            t.assignee=t.Assignee,
                                            t.State,t.due))
```

```{r}
t.consolidated_tasks <-  t.consolidated_tasks %>% mutate(f.condition1=(due <= app_vars$today),
                                                        
                                                        f.condition2=(due < (app_vars$today + app_vars$horizon_span1)),
                                                        f.condition3=(due < (app_vars$today + app_vars$horizon_span2)),
                                                        f.condition4=is.na(strftime(due)),
                                                        f.condition5=!(State %in% c("Complete","Closed")),
                                                        f.selection=((f.condition1 | f.condition3 |f.condition4)
                                                                     & f.condition5)) %>%
     filter(f.selection) %>%
     mutate(row_colour=ifelse(f.condition4,"X",
                              ifelse(f.condition1,"U",
                                     ifelse(f.condition2,"M",
                                            ifelse(f.condition3,"L","N")))))         
```



```{r}
#source("files/variables.R", echo = F, prompt.echo = "", spaced = F)

actions <- trello$checklists %>% mutate(name_cklst=name) %>%
    select(-id,-name,-pos) %>% unnest(checkItems) %>% select(-due) %>%
    left_join(chk_list_temp,by="id") %>%
    select(type=name_cklst,action,assignee,state,due, id,Project_id=idBoard,Task_id=idCard) %>%
    left_join((projects %>% select(Project_id,Project=Name)),by="Project_id") %>%
    filter(type=="Actions") %>% 
    left_join((app_vars$action_replace %>% select(state=Original,Replace)),by="state") %>%
    select(-type,-state) %>%
    mutate(State=Replace) %>%
    left_join((meetings  %>% 
                 select(id,url) %>% unique(.) %>%
                 select(Task_id=id,url)),by="Task_id")
  
actions
```


```{r}

 tibble(text=c("Last Update:"),time=c(paste(day(normalised_data$data_retrieved)," ",
       month(normalised_data$data_retrieved,label=TRUE), " ",
       year(normalised_data$data_retrieved)," -- ",
       hour(normalised_data$data_retrieved),
       ":",
      minute(normalised_data$data_retrieved),sep=""))) %>%
      mutate(text=cell_spec(text,align="right"),
             time=cell_spec(time,bold=T,align="left")) %>%
        kable(format = "html", escape = F, col.names = NULL) %>%
      kable_styling(full_width = F) 


```

