---
title: "Project's Report"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    social: menu
 #   source_code: embed
    theme: cerulean
---

```{r setup, include=FALSE}

library(tidyverse)
library(knitr)
library(kableExtra)
library(vistime)
library(lubridate)
library(plotly)
library(flexdashboard)




app_vars<-readRDS(file="./files/app_vars.rds")
source("./r/render.R", echo = F, prompt.echo = "", spaced = F)

rendered_data <-readRDS(file=app_vars$Rdata_file)

```

Start Page
=======================================================================

Row {data-height=5%}
-----------------------------------------------------------------------

```{r}
tibble(value=c("Project Management Report")) %>%
  kable(format = "html", escape = F,col.names = NULL,booktabs = T) %>%
      kable_styling(full_width = F) %>% 
  row_spec(1,bold = T,font_size = 20)
```


Row {data-height=10%}
-----------------------------------------------------------------------

```{r}
now_value <- paste(paste(lubridate::day(lubridate::now())," ",
            lubridate::month(lubridate::now(),label=TRUE), " ",
            lubridate::year(lubridate::now())," -- ",
            ifelse(lubridate::hour(lubridate::now())<10,paste("0",lubridate::hour(lubridate::now()),sep=""),lubridate::hour(lubridate::now())),
            ":",                                               
            ifelse(lubridate::minute(lubridate::now())<10,paste("0",lubridate::minute(lubridate::now()),sep=""),lubridate::minute(lubridate::now())),sep=""),sep=" ")

datevalue <- shiny::isolate(rendered_data$data_retrieved)

datevalue2 <-  paste(paste(lubridate::day(datevalue)," ",
                                   lubridate::month(datevalue,label=TRUE), " ",
                                   lubridate::year(datevalue)," -- ",
                                   ifelse(lubridate::hour(datevalue)<10,paste("0",lubridate::hour(datevalue),sep=""),lubridate::hour(datevalue)),
                                   ":",                                               
                              ifelse(lubridate::minute(datevalue)<10,paste("0",lubridate::minute(datevalue),sep=""),lubridate::minute(datevalue)),sep=""),sep=" ")

tibble(description=c("Report Created on:","Data Retrieved on:"),
       value=c(now_value,datevalue2)) %>%
  kable(format = "html", escape = F,col.names = NULL,booktabs = T) %>%
      kable_styling(full_width = F) 
```



Row {data-height=10%}
-----------------------------------------------------------------------

```{r}

tibble(Backlog=c(cell_spec("Backlog",align = "center"),
                 cell_spec(s.backlog<-shiny::isolate(rendered_data$render.stats_summary1$Backlog),align="right",bold=T)),
       Planning=c(cell_spec("Planning",align = "center"),
                 cell_spec(s.backlog<-shiny::isolate(rendered_data$render.stats_summary1$Planning),align="right",bold=T)),
       Progress=c(cell_spec("In Progress",align = "center"),
                 cell_spec(s.backlog<-shiny::isolate(rendered_data$render.stats_summary1$InProgress),align="right",bold=T)),
       Complete=c(cell_spec("Complete",align = "center"),
                 cell_spec(s.backlog<-shiny::isolate(rendered_data$render.stats_summary1$Complete),align="right",bold=T)),
       Space =c("", "") ,
       R=c(cell_spec("R",align = "center"),
                 cell_spec(s.backlog<-shiny::isolate(rendered_data$render.stats_summary1$R),align="right",bold=T)),
       A=c(cell_spec("A",align = "center"),
                 cell_spec(s.backlog<-shiny::isolate(rendered_data$render.stats_summary1$A),align="right",bold=T)),
       G=c(cell_spec("G",align = "center"),
                 cell_spec(s.backlog<-shiny::isolate(rendered_data$render.stats_summary1$G),align="right",bold=T)),
       
) %>%
      
        kable(format = "html", escape = F,booktabs = T,col.names = NULL) %>%
      kable_styling(full_width = F) %>%
  column_spec(1,width_min="7em",background = app_vars$project_kanban_background[which(app_vars$project_kanban_background$State=="Backlog"),]$hex,
              color=app_vars$t.default_colour ) %>%
  column_spec(2,width_min="7em",background = app_vars$project_kanban_background[which(app_vars$project_kanban_background$State=="Planning"),]$hex,
              color=app_vars$t.default_colour) %>%
  column_spec(3,width_min="7em",background = app_vars$project_kanban_background[which(app_vars$project_kanban_background$State=="In Progress"),]$hex,
              color=app_vars$t.default_colour) %>%
  column_spec(4,width_min="7em",background = app_vars$project_kanban_background[which(app_vars$project_kanban_background$State=="Complete"),]$hex,
              color=app_vars$t.default_colour ) %>%
    column_spec(6,width_min="7em",background = app_vars$status_colours[which(app_vars$status_colours$colour_short=="R"),]$hex,
              color="white" ) %>%
    column_spec(7,width_min="7em",background = app_vars$status_colours[which(app_vars$status_colours$colour_short=="A"),]$hex,
              color="white") %>%
    column_spec(8,width_min="7em",background = app_vars$status_colours[which(app_vars$status_colours$colour_short=="G"),]$hex,
              color="white") 
```



Row {data-height=10%}
-----------------------------------------------------------------------

```{r}
tibble(LateStart=c(cell_spec("Late Start",align = "center"),
                 cell_spec(s.backlog<-shiny::isolate(rendered_data$render.stats_summary2$late.start),align="right",bold=T)),
       Overdue=c(cell_spec("Overdue",align = "center"),
                 cell_spec(s.backlog<-shiny::isolate(rendered_data$render.stats_summary2$overdue),align="right",bold=T)),
        LateTasks=c(cell_spec("Late Tasks",align = "center"),
                 cell_spec(s.backlog<-shiny::isolate(rendered_data$render.stats_summary2$late.tasks),align="right",bold=T)),
        IssuesR=c(cell_spec("Issues - R",align = "center"),
                 cell_spec(s.backlog<-shiny::isolate(rendered_data$render.stats_summary2$issue.R),align="right",bold=T)),
        IssuesA=c(cell_spec("Issues - A",align = "center"),
                 cell_spec(s.backlog<-shiny::isolate(rendered_data$render.stats_summary2$issue.A),align="right",bold=T)),
        OpenActions=c(cell_spec("Open Actions",align = "center"),
                 cell_spec(s.backlog<-shiny::isolate(rendered_data$render.stats_summary2$open.actions),align="right",bold=T))
) %>% 
  kable(format = "html", escape = F,booktabs = T,col.names = NULL) %>%
      kable_styling(full_width = F) %>%
  column_spec(1,width_min="7em",background = app_vars$status_colours[which(app_vars$status_colours$colour_short=="NA"),]$hex,
              color="white" ) %>%
  column_spec(2,width_min="7em",background = app_vars$status_colours[which(app_vars$status_colours$colour_short=="NA"),]$hex,
              color="white"  ) %>%
  column_spec(3,width_min="7em",background = app_vars$status_colours[which(app_vars$status_colours$colour_short=="NA"),]$hex,
              color="white"  ) %>%
  column_spec(4,width_min="7em",background = app_vars$status_colours[which(app_vars$status_colours$colour_short=="R"),]$hex,
              color="white") %>%
  column_spec(5,width_min="7em",background = app_vars$status_colours[which(app_vars$status_colours$colour_short=="A"),]$hex,
              color="white"  ) %>%
  column_spec(6,width_min="7em",background = app_vars$status_colours[which(app_vars$status_colours$colour_short=="NA"),]$hex,
              color="white"  ) 
```


Kanban
=======================================================================

Row {data-height=80%}
-----------------------------------------------------------------------


### Backlog

```{r}

shiny::isolate(rendered_data$render.kanban$project_list_backlog)   %>%
  row_spec(1:shiny::isolate(rendered_data$render.kanban$row_values), extra_css = "border-bottom: 1px solid white")

```



### Planning

```{r}

shiny::isolate(rendered_data$render.kanban$project_list_planning)   %>%
  row_spec(1:shiny::isolate(rendered_data$render.kanban$row_values), extra_css = "border-bottom: 1px solid white")

```




### In Progress

```{r}
shiny::isolate(rendered_data$render.kanban$project_list_active)    %>%
  row_spec(1:shiny::isolate(rendered_data$render.kanban$row_values), extra_css = "border-bottom: 1px solid white")
```




### Complete

```{r}
shiny::isolate(rendered_data$render.kanban$project_list_complete)   %>%
  row_spec(1:shiny::isolate(rendered_data$render.kanban$row_values), extra_css = "border-bottom: 1px solid white")

```



Roadmap
=======================================================================


```{r}
 shiny::isolate(rendered_data$render.roadmap)

```


Projects' Summaries
=======================================================================


```{r}
shiny::isolate(rendered_data$render.projects)
```


Issues
=======================================================================


```{r}
shiny::isolate(rendered_data$render.issues)
```


Actions
=======================================================================


```{r}
shiny::isolate(rendered_data$render.actions)
```



